# Generated by Django 3.0.5 on 2020-04-25 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='April',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='December',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='February',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='January',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='March',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('afternoon', models.CharField(max_length=100)),
                ('night', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='November',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='October',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(help_text='Mobile number', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='September',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afternoon', models.IntegerField()),
                ('night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_number', models.IntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('mob_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Mobile number', max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
